### ISSUE TITLE
Latest Matplotlib is not compatible

### ISSUE THREAD

**Issue by BrosnanYuen** [siplab-gt/cleo#50]
Installing matplotlib-3.9.0 breaks cleosim visualization functions

  File "/home/brosnan/.conda/envs/cleosim/lib/python3.10/site-packages/cleo/light/light.py", line 437, in add_self_to_plot
    handles = ax.get_legend().legendHandles
AttributeError: 'Legend' object has no attribute 'legendHandles'

However, matplotlib-3.8.2 works.

**Comment by kjohnsen** [comment]
Thanks for reporting! I'll get to it soon

**Comment by kjohnsen** [comment]
Done. Let me know if you run into any more problems!
